/*
 * ArchE
 * Copyright (c) 2012 Carnegie Mellon University.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following acknowledgments and disclaimers.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. All advertising materials for third-party software mentioning features or
 * use of this software must display the following disclaimer:
 *
 * “Neither Carnegie Mellon University nor its Software Engineering Institute
 * have reviewed or endorsed this software”
 *
 * 4. The names “Carnegie Mellon University,” and/or “Software Engineering
 * Institute" shall not be used to endorse or promote products derived from
 * this software without prior written permission. For written permission,
 * please contact permission@sei.cmu.edu.
 *
 * 5. Redistributions of any form whatsoever must retain the following
 * acknowledgment:
 *
 * Copyright 2012 Carnegie Mellon University.
 *
 * This material is based upon work funded and supported by the United States
 * Department of Defense under Contract No. FA8721-05-C-0003 with Carnegie
 * Mellon University for the operation of the Software Engineering Institute, a
 * federally funded research and development center.
 *
 * NO WARRANTY
 *
 * THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL
 * IS FURNISHED ON AN “AS-IS” BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO
 * WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER
 * INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
 * MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL.
 * CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH
 * RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 */

package edu.cmu.sei.ORM.model;

import java.util.List;

/** Class _Auctionitem was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Auctionitem extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String CONDITION_PROPERTY = "condition";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ENDS_PROPERTY = "ends";
    public static final String SHORT_DESCRIPTION_PROPERTY = "shortDescription";
    public static final String BID_ARRAY_PROPERTY = "bidArray";
    public static final String TO_AUCTIONUSER_PROPERTY = "toAuctionuser";
    public static final String TO_BID_PROPERTY = "toBid";

    public static final String ID_PK_COLUMN = "id";

    public void setCondition(Integer condition) {
        writeProperty("condition", condition);
    }
    public Integer getCondition() {
        return (Integer)readProperty("condition");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setEnds(java.util.Date ends) {
        writeProperty("ends", ends);
    }
    public java.util.Date getEnds() {
        return (java.util.Date)readProperty("ends");
    }
    
    
    public void setShortDescription(String shortDescription) {
        writeProperty("shortDescription", shortDescription);
    }
    public String getShortDescription() {
        return (String)readProperty("shortDescription");
    }
    
    
    public void addToBidArray(Bid obj) {
        addToManyTarget("bidArray", obj, true);
    }
    public void removeFromBidArray(Bid obj) {
        removeToManyTarget("bidArray", obj, true);
    }
    public List getBidArray() {
        return (List)readProperty("bidArray");
    }
    
    
    public void setToAuctionuser(Auctionuser toAuctionuser) {
        setToOneTarget("toAuctionuser", toAuctionuser, true);
    }

    public Auctionuser getToAuctionuser() {
        return (Auctionuser)readProperty("toAuctionuser");
    } 
    
    
    public void setToBid(Bid toBid) {
        setToOneTarget("toBid", toBid, true);
    }

    public Bid getToBid() {
        return (Bid)readProperty("toBid");
    } 
    
    
}
