/*
 * ArchE
 * Copyright (c) 2012 Carnegie Mellon University.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following acknowledgments and disclaimers.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. All advertising materials for third-party software mentioning features or
 * use of this software must display the following disclaimer:
 *
 * “Neither Carnegie Mellon University nor its Software Engineering Institute
 * have reviewed or endorsed this software”
 *
 * 4. The names “Carnegie Mellon University,” and/or “Software Engineering
 * Institute" shall not be used to endorse or promote products derived from
 * this software without prior written permission. For written permission,
 * please contact permission@sei.cmu.edu.
 *
 * 5. Redistributions of any form whatsoever must retain the following
 * acknowledgment:
 *
 * Copyright 2012 Carnegie Mellon University.
 *
 * This material is based upon work funded and supported by the United States
 * Department of Defense under Contract No. FA8721-05-C-0003 with Carnegie
 * Mellon University for the operation of the Software Engineering Institute, a
 * federally funded research and development center.
 *
 * NO WARRANTY
 *
 * THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL
 * IS FURNISHED ON AN “AS-IS” BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO
 * WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER
 * INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
 * MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL.
 * CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH
 * RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 */

package edu.cmu.sei.ORM.model;

import java.util.List;

/** Class _Bid was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _Bid extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String AMOUNT_PROPERTY = "amount";
    public static final String DATETIME_PROPERTY = "datetime";
    public static final String IS_BUY_NOW_PROPERTY = "isBuyNow";
    public static final String AUCTIONITEM_ARRAY_PROPERTY = "auctionitemArray";
    public static final String TO_AUCTIONITEM_PROPERTY = "toAuctionitem";
    public static final String TO_AUCTIONUSER_PROPERTY = "toAuctionuser";

    public static final String ID_PK_COLUMN = "id";

    public void setAmount(Float amount) {
        writeProperty("amount", amount);
    }
    public Float getAmount() {
        return (Float)readProperty("amount");
    }
    
    
    public void setDatetime(java.util.Date datetime) {
        writeProperty("datetime", datetime);
    }
    public java.util.Date getDatetime() {
        return (java.util.Date)readProperty("datetime");
    }
    
    
    public void setIsBuyNow(String isBuyNow) {
        writeProperty("isBuyNow", isBuyNow);
    }
    public String getIsBuyNow() {
        return (String)readProperty("isBuyNow");
    }
    
    
    public void addToAuctionitemArray(Auctionitem obj) {
        addToManyTarget("auctionitemArray", obj, true);
    }
    public void removeFromAuctionitemArray(Auctionitem obj) {
        removeToManyTarget("auctionitemArray", obj, true);
    }
    public List getAuctionitemArray() {
        return (List)readProperty("auctionitemArray");
    }
    
    
    public void setToAuctionitem(Auctionitem toAuctionitem) {
        setToOneTarget("toAuctionitem", toAuctionitem, true);
    }

    public Auctionitem getToAuctionitem() {
        return (Auctionitem)readProperty("toAuctionitem");
    } 
    
    
    public void setToAuctionuser(Auctionuser toAuctionuser) {
        setToOneTarget("toAuctionuser", toAuctionuser, true);
    }

    public Auctionuser getToAuctionuser() {
        return (Auctionuser)readProperty("toAuctionuser");
    } 
    
    
}
