/*
 * ArchE
 * Copyright (c) 2012 Carnegie Mellon University.
 * All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following acknowledgments and disclaimers.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. All advertising materials for third-party software mentioning features or
 * use of this software must display the following disclaimer:
 *
 * “Neither Carnegie Mellon University nor its Software Engineering Institute
 * have reviewed or endorsed this software”
 *
 * 4. The names “Carnegie Mellon University,” and/or “Software Engineering
 * Institute" shall not be used to endorse or promote products derived from
 * this software without prior written permission. For written permission,
 * please contact permission@sei.cmu.edu.
 *
 * 5. Redistributions of any form whatsoever must retain the following
 * acknowledgment:
 *
 * Copyright 2012 Carnegie Mellon University.
 *
 * This material is based upon work funded and supported by the United States
 * Department of Defense under Contract No. FA8721-05-C-0003 with Carnegie
 * Mellon University for the operation of the Software Engineering Institute, a
 * federally funded research and development center.
 *
 * NO WARRANTY
 *
 * THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING INSTITUTE MATERIAL
 * IS FURNISHED ON AN “AS-IS” BASIS. CARNEGIE MELLON UNIVERSITY MAKES NO
 * WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER
 * INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
 * MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE MATERIAL.
 * CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND WITH
 * RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
 */

package edu.cmu.sei.ORM.model;

/** Class _MainScenarios was generated by Cayenne.
  * It is probably a good idea to avoid changing this class manually, 
  * since it may be overwritten next time code is regenerated. 
  * If you need to make any customizations, please use subclass. 
  */
public class _MainScenarios extends org.objectstyle.cayenne.CayenneDataObject {

    public static final String ARTIFACT_TEXT_PROPERTY = "artifactText";
    public static final String ARTIFACT_TYPE_PROPERTY = "artifactType";
    public static final String ARTIFACT_UNIT_PROPERTY = "artifactUnit";
    public static final String ARTIFACT_VALUE_PROPERTY = "artifactValue";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ENVIRONMENT_TEXT_PROPERTY = "environmentText";
    public static final String ENVIRONMENT_TYPE_PROPERTY = "environmentType";
    public static final String ENVIRONMENT_UNIT_PROPERTY = "environmentUnit";
    public static final String ENVIRONMENT_VALUE_PROPERTY = "environmentValue";
    public static final String FACTID_PROPERTY = "factid";
    public static final String ID_PROPERTY = "id";
    public static final String MEASURE_TEXT_PROPERTY = "measureText";
    public static final String MEASURE_TYPE_PROPERTY = "measureType";
    public static final String MEASURE_UNIT_PROPERTY = "measureUnit";
    public static final String MEASURE_VALUE_PROPERTY = "measureValue";
    public static final String QUALITY_PROPERTY = "quality";
    public static final String RESPONSE_TEXT_PROPERTY = "responseText";
    public static final String RESPONSE_TYPE_PROPERTY = "responseType";
    public static final String RESPONSE_UNIT_PROPERTY = "responseUnit";
    public static final String RESPONSE_VALUE_PROPERTY = "responseValue";
    public static final String SOURCE_TEXT_PROPERTY = "sourceText";
    public static final String SOURCE_TYPE_PROPERTY = "sourceType";
    public static final String SOURCE_UNIT_PROPERTY = "sourceUnit";
    public static final String SOURCE_VALUE_PROPERTY = "sourceValue";
    public static final String STATE_PROPERTY = "state";
    public static final String STIMULUS_TEXT_PROPERTY = "stimulusText";
    public static final String STIMULUS_TYPE_PROPERTY = "stimulusType";
    public static final String STIMULUS_UNIT_PROPERTY = "stimulusUnit";
    public static final String STIMULUS_VALUE_PROPERTY = "stimulusValue";
    public static final String TO_VERSIONS_PROPERTY = "toVersions";

    public static final String UID_PK_COLUMN = "uid";

    public void setArtifactText(String artifactText) {
        writeProperty("artifactText", artifactText);
    }
    public String getArtifactText() {
        return (String)readProperty("artifactText");
    }
    
    
    public void setArtifactType(String artifactType) {
        writeProperty("artifactType", artifactType);
    }
    public String getArtifactType() {
        return (String)readProperty("artifactType");
    }
    
    
    public void setArtifactUnit(String artifactUnit) {
        writeProperty("artifactUnit", artifactUnit);
    }
    public String getArtifactUnit() {
        return (String)readProperty("artifactUnit");
    }
    
    
    public void setArtifactValue(Double artifactValue) {
        writeProperty("artifactValue", artifactValue);
    }
    public Double getArtifactValue() {
        return (Double)readProperty("artifactValue");
    }
    
    
    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }
    
    
    public void setEnvironmentText(String environmentText) {
        writeProperty("environmentText", environmentText);
    }
    public String getEnvironmentText() {
        return (String)readProperty("environmentText");
    }
    
    
    public void setEnvironmentType(String environmentType) {
        writeProperty("environmentType", environmentType);
    }
    public String getEnvironmentType() {
        return (String)readProperty("environmentType");
    }
    
    
    public void setEnvironmentUnit(String environmentUnit) {
        writeProperty("environmentUnit", environmentUnit);
    }
    public String getEnvironmentUnit() {
        return (String)readProperty("environmentUnit");
    }
    
    
    public void setEnvironmentValue(Double environmentValue) {
        writeProperty("environmentValue", environmentValue);
    }
    public Double getEnvironmentValue() {
        return (Double)readProperty("environmentValue");
    }
    
    
    public void setFactid(String factid) {
        writeProperty("factid", factid);
    }
    public String getFactid() {
        return (String)readProperty("factid");
    }
    
    
    public void setId(String id) {
        writeProperty("id", id);
    }
    public String getId() {
        return (String)readProperty("id");
    }
    
    
    public void setMeasureText(String measureText) {
        writeProperty("measureText", measureText);
    }
    public String getMeasureText() {
        return (String)readProperty("measureText");
    }
    
    
    public void setMeasureType(String measureType) {
        writeProperty("measureType", measureType);
    }
    public String getMeasureType() {
        return (String)readProperty("measureType");
    }
    
    
    public void setMeasureUnit(String measureUnit) {
        writeProperty("measureUnit", measureUnit);
    }
    public String getMeasureUnit() {
        return (String)readProperty("measureUnit");
    }
    
    
    public void setMeasureValue(Double measureValue) {
        writeProperty("measureValue", measureValue);
    }
    public Double getMeasureValue() {
        return (Double)readProperty("measureValue");
    }
    
    
    public void setQuality(String quality) {
        writeProperty("quality", quality);
    }
    public String getQuality() {
        return (String)readProperty("quality");
    }
    
    
    public void setResponseText(String responseText) {
        writeProperty("responseText", responseText);
    }
    public String getResponseText() {
        return (String)readProperty("responseText");
    }
    
    
    public void setResponseType(String responseType) {
        writeProperty("responseType", responseType);
    }
    public String getResponseType() {
        return (String)readProperty("responseType");
    }
    
    
    public void setResponseUnit(String responseUnit) {
        writeProperty("responseUnit", responseUnit);
    }
    public String getResponseUnit() {
        return (String)readProperty("responseUnit");
    }
    
    
    public void setResponseValue(Double responseValue) {
        writeProperty("responseValue", responseValue);
    }
    public Double getResponseValue() {
        return (Double)readProperty("responseValue");
    }
    
    
    public void setSourceText(String sourceText) {
        writeProperty("sourceText", sourceText);
    }
    public String getSourceText() {
        return (String)readProperty("sourceText");
    }
    
    
    public void setSourceType(String sourceType) {
        writeProperty("sourceType", sourceType);
    }
    public String getSourceType() {
        return (String)readProperty("sourceType");
    }
    
    
    public void setSourceUnit(String sourceUnit) {
        writeProperty("sourceUnit", sourceUnit);
    }
    public String getSourceUnit() {
        return (String)readProperty("sourceUnit");
    }
    
    
    public void setSourceValue(Double sourceValue) {
        writeProperty("sourceValue", sourceValue);
    }
    public Double getSourceValue() {
        return (Double)readProperty("sourceValue");
    }
    
    
    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }
    
    
    public void setStimulusText(String stimulusText) {
        writeProperty("stimulusText", stimulusText);
    }
    public String getStimulusText() {
        return (String)readProperty("stimulusText");
    }
    
    
    public void setStimulusType(String stimulusType) {
        writeProperty("stimulusType", stimulusType);
    }
    public String getStimulusType() {
        return (String)readProperty("stimulusType");
    }
    
    
    public void setStimulusUnit(String stimulusUnit) {
        writeProperty("stimulusUnit", stimulusUnit);
    }
    public String getStimulusUnit() {
        return (String)readProperty("stimulusUnit");
    }
    
    
    public void setStimulusValue(Double stimulusValue) {
        writeProperty("stimulusValue", stimulusValue);
    }
    public Double getStimulusValue() {
        return (Double)readProperty("stimulusValue");
    }
    
    
    public void setToVersions(Versions toVersions) {
        setToOneTarget("toVersions", toVersions, true);
    }

    public Versions getToVersions() {
        return (Versions)readProperty("toVersions");
    } 
    
    
}
